### ISSUE TITLE
我想下载一个pdf进行阅读，应该怎么弄？

### ISSUE THREAD

**Issue by sunyonggang** [chenryn/logstash-best-practice-cn#16]
不好意思，对于这块不怎么熟；
能不能提供一个pdf的版本？像这样[elastcisearch](https://www.gitbook.com/book/looly/elasticsearch-the-definitive-guide-cn/details)

**Comment by chenryn** [comment]
http://kibana.logstash.es/

2015-10-05 16:05 GMT+08:00 sunyonggang <notifications@github.com>:

**Comment by sunyonggang** [comment]
3q，找到了
