### ISSUE TITLE
nxlog ssl

### ISSUE THREAD

**Issue by leitu** [chenryn/logstash-best-practice-cn#3]
如果已纯粹的tcp 来做的话不那么安全。

**Comment by chenryn** [comment]
@s270987763 提交的章节。两位看看是添补nxlog的ssl配置方案还是如何处理？

**Comment by myhero520** [comment]
问题：如果说启动一个logstash，想收多个topic（如t1,t2,t3）的消息，可以么？如果可以该如何配置？

**Comment by leitu** [comment]
close it since it was 2 years ago
